# Generated by Django 4.1.3 on 2022-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_quantity_alter_food_wasted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='wasted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
