# Generated by Django 4.1.3 on 2022-11-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_quantity_alter_food_wasted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWasteFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(max_length=200)),
                ('source_name', models.CharField(max_length=80)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
